version: '1.0'
name: pipeline-20230928
displayName: pipeline-20230928
triggers:
  trigger: auto
stages:
  - name: stage-89a3bf2d
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: '10.3'
        commands:
          - ./build.sh init && ./build.sh
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
